### ISSUE TITLE
fails with my realtek usb wifi stik

### ISSUE THREAD

**Issue by nutpantz** [ashtum/ashmon#1]
just shows 000s across the board

my device name is

wlx000d81a24e54

lsusb

Bus 001 Device 008: ID 0bda:8172 Realtek Semiconductor Corp. RTL8191SU 802.11n WLAN Adapter

but please kkep working on this as ubuntu definatly needs it and please build a .deb file

**Comment by ashtum** [comment]
@nutpantz , 
this software is independent from device driver and must work with all network device without problem because it get information from linux default path : `/sys/class/net/{your_dev_name}/statistics/`
how you run program ? in this case you must run it with : `ashmon wlx000d81a24e54` command

**Comment by nutpantz** [comment]
Yep that's exactly how I run it.
I either get all zeros or large negativenegative numbers.
![img_20160609_081050_20160609_081242](https://cloud.githubusercontent.com/assets/12160507/15934873/0055c2d0-2e1a-11e6-8c34-5a27c14a40cd.jpg)

**Comment by ashtum** [comment]
It is interesting ,
please run this command twice (whit 2 second interval) and put the results for analysis : `tail -n +1 -- /sys/class/net/wlx000d81a24e54/statistics/*`

**Comment by nutpantz** [comment]
guestuser1@Guestsystem:~$ tail -n +1 -- /sys/class/net/wlx000d81a24e54/statistics/*
==> /sys/class/net/wlx000d81a24e54/statistics/collisions <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/multicast <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_bytes <==
1953798080

==> /sys/class/net/wlx000d81a24e54/statistics/rx_compressed <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_crc_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_dropped <==
260241

==> /sys/class/net/wlx000d81a24e54/statistics/rx_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_fifo_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_frame_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_length_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_missed_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_over_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_packets <==
1294463

==> /sys/class/net/wlx000d81a24e54/statistics/tx_aborted_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_bytes <==
63986288

==> /sys/class/net/wlx000d81a24e54/statistics/tx_carrier_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_compressed <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_dropped <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_fifo_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_heartbeat_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_packets <==
716200

==> /sys/class/net/wlx000d81a24e54/statistics/tx_window_errors <==
0
guestuser1@Guestsystem:~$ tail -n +1 -- /sys/class/net/wlx000d81a24e54/statistics/*
==> /sys/class/net/wlx000d81a24e54/statistics/collisions <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/multicast <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_bytes <==
1964976483

==> /sys/class/net/wlx000d81a24e54/statistics/rx_compressed <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_crc_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_dropped <==
261469

==> /sys/class/net/wlx000d81a24e54/statistics/rx_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_fifo_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_frame_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_length_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_missed_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_over_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/rx_packets <==
1301859

==> /sys/class/net/wlx000d81a24e54/statistics/tx_aborted_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_bytes <==
64327126

==> /sys/class/net/wlx000d81a24e54/statistics/tx_carrier_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_compressed <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_dropped <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_fifo_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_heartbeat_errors <==
0

==> /sys/class/net/wlx000d81a24e54/statistics/tx_packets <==
720078

==> /sys/class/net/wlx000d81a24e54/statistics/tx_window_errors <==
0

something like that??

**Comment by ashtum** [comment]
[debug.zip](https://github.com/ashtum/ashmon/files/307367/debug.zip)
run this version (for a couple of second) that print information for find fail segment .

**Comment by nutpantz** [comment]
guestuser1@Guestsystem:~/Downloads/debug$ ./ashmon_64bit wlx000d81a24e54
path  : /sys/class/net/wlx000d81a24e54/statistics/rx_bytes
rxs  : 9392021
rxi  : 9392021
txi  : 701545
max  : 0
path  : /sys/class/net/wlx000d81a24/statistics/rx_bytes
rxs  : rxi  : 0
txi  : 0
max  : -701545
path  : /sys/class/net/wlx000d81a24�K��/statistics/rx_bytes
rxs  : rxi  : 0
txi  : 0
max  : -701545
path  : /sys/class/net/wlx000d81a24�K��/statistics/rx_bytes
rxs  : rxi  : 0
txi  : 0

.......

like this???

**Comment by ashtum** [comment]
```
path : /sys/class/net/wlx000d81a24e54/statistics/rx_bytes
rxs : 9392021
rxi : 9392021
txi : 701545
max : 0
path : /sys/class/net/wlx000d81a24/statistics/rx_bytes
rxs : rxi : 0
txi : 0
max : -701545
path : /sys/class/net/wlx000d81a24�K��/statistics/rx_bytes
rxs : rxi : 0
txi : 0
max : -701545
```
This is the problem:
`char dev_name[10];`
I fixed it , you can download new version from releases .
Thanks for your report , i hope you enjoyed it .

**Comment by nutpantz** [comment]
working now... Thanks for the very usefull app..
i would love to see it adopted by ubuntu 
and would love to see a deb installer some day..
(is there any way to have it open in the same place each time? or should i open that a a new issue?)

**Comment by ashtum** [comment]
>  (is there any way to have it open in the same place each time? or should i open that a a new issue?)
for what ? deb package installer  ?
