### ISSUE TITLE
Dies with X font error on Arch

### ISSUE THREAD

**Issue by Nemin32** [ashtum/ashmon#3]
```
X Error of failed request:  BadName (named color or font does not exist)
  Major opcode of failed request:  45 (X_OpenFont)
  Serial number of failed request:  17
  Current serial number in output stream:  35
```

I believe the issue is likely in [gui.hpp on line 66.](https://github.com/ashtum/gambal/blob/master/src/gui.hpp#L66) Perhaps giving the option to the user to supply their own font name would solve this issue?

Thanks for your time, keep up the good work!

**Comment by ashtum** [comment]
Thank you for report, that's a wrong assumption I have made here, can you change line 66 to this and test again:
` std::vector<style> styles_{ { "normal", "6x13", {}, 2, 6, 13, 158 } };`
I will test and fix problem on arch very soon. i didn't see this problem on other distros.

**Comment by Nemin32** [comment]
Yes, it does work when I change the line, however, I am not able to set the font weight to bold. Is this intentional? The arrows next to the "normal" text are grayed out.

**Comment by ashtum** [comment]
Yes, bold style shouldn't work after change, because we removed bold entry in styles. i just wanted to make sure the problem is with "7x13B" font.
I think there is no 7x13 font in this `/usr/share/fonts/misc` or this `./share/fonts/X11/misc/` path on your machine.
I'm installing arch on vm now to narrow down the issue.

**Comment by ashtum** [comment]
What is your desktop environment ?

**Comment by Nemin32** [comment]
I'm using KDE with SDDM as DM.

**Comment by ashtum** [comment]
I think you can solve the issue by installing xorg-fonts-misc package.

**Comment by Nemin32** [comment]
I've installed it, but I'm still getting the same error.

**Comment by RedsonBr140** [comment]
I'm also having this error, I use Arch with Bspwm and ly as DM.

**Comment by Nemin32** [comment]
Logging out and logging in after installing xorg-fonts-misc solved the issue. I recommend putting the dependency in the README file. Have a nice day.
