### ISSUE TITLE
Native Wayland support ?

### ISSUE THREAD

**Issue by chromer030** [ashtum/ashmon#7]

**Comment by ashtum** [comment]
Can you explain what's the point of it?

**Comment by chromer030** [comment]
Support of running the tool under Wayland in native mode without using x server (xwayland)

**Comment by ashtum** [comment]
I mean what's the point of supporting native wayland and not using xwayland? What is the reason behind it?

**Comment by chromer030** [comment]
Xorg is going to be retired.
https://www.theregister.com/2020/10/30/x_server_lead_maintainer_declares/

**Comment by ashtum** [comment]
> Xorg is going to be retired. https://www.theregister.com/2020/10/30/x_server_lead_maintainer_declares/

Yes, but it doesn't mean XWayland is going to be removed from distros anytime soon.
